# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 20:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carwash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('calle', models.CharField(max_length=140)),
                ('no_calle', models.CharField(max_length=140)),
                ('colonia', models.CharField(max_length=140)),
                ('municipio', models.CharField(default='Aguascalientes', max_length=140)),
                ('estado', models.CharField(default='Aguascalientes', max_length=140)),
                ('pais', models.CharField(default='Mexico', max_length=140)),
                ('cp', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('horario_abierto', models.TimeField()),
                ('horario_cerrado', models.TimeField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Activo', 1), ('Suspendido', 2), ('Eliminado', 3), ('Reactivado', 4)], max_length=140)),
                ('logo', models.ImageField(upload_to='static/images/logoCarwash/')),
                ('propietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
