# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 20:46
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_auto_20170518_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carwash',
            options={'verbose_name_plural': 'Carwash'},
        ),
        migrations.AddField(
            model_name='carwash',
            name='ubicacion',
            field=geoposition.fields.GeopositionField(default=1, max_length=42),
            preserve_default=False,
        ),
    ]
