# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_auto_20170518_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='horario_abierto',
            field=models.TimeField(verbose_name='Abierto a las'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='horario_cerrado',
            field=models.TimeField(verbose_name='Cerrado a las'),
        ),
        migrations.AlterField(
            model_name='carwash',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
