# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_auto_20170518_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='carwash',
            name='dias_laborales',
            field=models.ManyToManyField(to='negocios.Semana'),
        ),
    ]
