# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0005_auto_20170518_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalago_Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('servicio', models.CharField(max_length=140)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.Carwash')),
            ],
        ),
    ]
