# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0006_catalago_servicios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalago_servicios',
            options={'verbose_name_plural': 'Catalogo de Servicios'},
        ),
    ]
