# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0007_auto_20170518_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalago_servicios',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
