# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0009_auto_20170519_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carwash',
            name='logo',
            field=models.ImageField(upload_to='static/assets/images/logoCarwash/'),
        ),
    ]
