# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 16:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('negocios', '0009_auto_20170519_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_venta', models.IntegerField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_Adquiridos_Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_original', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.IntegerField()),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.Catalago_Servicios')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Orden_Venta')),
            ],
        ),
    ]
