# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0009_auto_20170519_1053'),
        ('ventas', '0003_servicios_adquiridos_venta_carwash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios_adquiridos_venta',
            name='carwash',
        ),
        migrations.AddField(
            model_name='orden_venta',
            name='carwash',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='negocios.Carwash'),
            preserve_default=False,
        ),
    ]
