# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-25 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20170521_1337'),
        ('ventas', '0006_auto_20170519_1546'),
    ]

    operations = [
    ]
