# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo_perfiles',
            options={'verbose_name_plural': 'Catalago de Perfiles'},
        ),
    ]
