# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20170518_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo_perfiles',
            name='nombre',
        ),
        migrations.AddField(
            model_name='catalogo_perfiles',
            name='colonia',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogo_perfiles',
            name='direccion',
            field=models.CharField(default='centro', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogo_perfiles',
            name='estado',
            field=models.CharField(default='Aguascalientes', max_length=140),
        ),
        migrations.AddField(
            model_name='catalogo_perfiles',
            name='municipio',
            field=models.CharField(default='Aguascalientes', max_length=140),
        ),
        migrations.AddField(
            model_name='catalogo_perfiles',
            name='pais',
            field=models.CharField(default='Mexico', max_length=140),
        ),
        migrations.AddField(
            model_name='catalogo_perfiles',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
