# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-24 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_auto_20170523_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo_perfiles',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/images/avatars/'),
        ),
    ]
