# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_auto_20170524_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='direccion',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
